version: '3'
services:
  database:
    restart: unless-stopped
    image: postgres:alpine
    environment:
    - POSTGRES_DB=bitcart
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123@
    volumes:
    - dbdata:/var/lib/postgresql/data
    expose:
    - '5432'
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    container_name: nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - nginx_conf:/etc/nginx/conf.d
    - nginx_vhost:/etc/nginx/vhost.d
    - nginx_html:/usr/share/nginx/html
    - nginx_certs:/etc/nginx/certs:ro
    links:
    - backend
    - frontend
  nginx-gen:
    restart: unless-stopped
    image: jwilder/docker-gen:0.7.0
    container_name: nginx-gen
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    - nginx_conf:/etc/nginx/conf.d
    - nginx_vhost:/etc/nginx/vhost.d
    - nginx_html:/usr/share/nginx/html
    - nginx_certs:/etc/nginx/certs:ro
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s
      /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    links:
    - nginx
  letsencrypt-nginx-proxy-companion:
    restart: unless-stopped
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - nginx_conf:/etc/nginx/conf.d
    - nginx_vhost:/etc/nginx/vhost.d
    - nginx_html:/usr/share/nginx/html
    - nginx_certs:/etc/nginx/certs:rw
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx
      ACME_CA_URI: ${ACME_CA_URI:-https://acme-v01.api.letsencrypt.org/directory}
    links:
    - nginx-gen
  redis:
    restart: unless-stopped
    image: redis:alpine
    expose:
    - '6379'
  dramatiq:
    restart: unless-stopped
    image: mrnaif/bitcart:stable
    command: python3 manage.py rundramatiq --no-reload
  daemon:
    restart: unless-stopped
    image: mrnaif/bitcart:stable
    command: python3 daemons/btc.py
    expose:
    - '5000'
  backend:
    restart: unless-stopped
    image: mrnaif/bitcart:stable
    command: /usr/local/bin/docker-entrypoint.sh
    environment:
      DB_PORT: 5432
      DB_HOST: database
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 8000
      VIRTUAL_HOST: ${BITCART_HOST}
      VIRTUAL_HOST_NAME: bitcart-backend
      LETSENCRYPT_HOST: ${BITCART_HOST}
      LETSENCRYPT_EMAIL: ${BITCART_LETSENCRYPT_EMAIL:-<no value>}
    expose:
    - '8000'
    volumes:
    - ./conf:/home/electrum/site/conf
    depends_on:
    - database
    - redis
    - dramatiq
    - daemon
    links:
    - database
    - redis
    - dramatiq
    - daemon
  frontend:
    restart: unless-stopped
    image: mrnaif/bitcart-frontend
    expose:
    - '3000'
    command: npm start
    environment:
      BITCART_FRONTEND_URL: ${BITCART_FRONTEND_URL}
      BITCART_FRONTEND_TOKEN: ${BITCART_FRONTEND_TOKEN}
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: ${BITCART_FRONTEND_HOST}
      VIRTUAL_HOST_NAME: bitcart-frontend
      LETSENCRYPT_HOST: ${BITCART_FRONTEND_HOST}
      LETSENCRYPT_EMAIL: ${BITCART_LETSENCRYPT_EMAIL:-<no value>}
    links:
    - backend
volumes:
  dbdata: null
  nginx_conf: null
  nginx_vhost: null
  nginx_html: null
  nginx_certs: null
