services:
  frontend:
    restart: unless-stopped
    image: mrnaif/bitcart-frontend
    expose:
      - "3000"
    command: npm start
    environment:
      BITCART_FRONTEND_URL: ${BITCART_FRONTEND_URL}
      BITCART_FRONTEND_TOKEN: ${BITCART_FRONTEND_TOKEN}
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: ${BITCART_FRONTEND_HOST}
      VIRTUAL_HOST_NAME: "bitcart-frontend"
      LETSENCRYPT_HOST: ${BITCART_FRONTEND_HOST}
      LETSENCRYPT_EMAIL: ${BITCART_LETSENCRYPT_EMAIL:-<no value>}